-- AlterTable
ALTER TABLE "Booking" ADD COLUMN     "createdAtBooking" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "distanceKm" DOUBLE PRECISION,
ADD COLUMN     "fuelEnd" DOUBLE PRECISION,
ADD COLUMN     "fuelStart" DOUBLE PRECISION,
ADD COLUMN     "fuelUsed" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN     "currentFuel" DOUBLE PRECISION NOT NULL DEFAULT 100,
ALTER COLUMN "lastService" DROP NOT NULL;
